name: Acceptance Tests
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    name: ${{ matrix.devnet-config }}-sysgo-tests
    strategy:
      fail-fast: false
      matrix:
        devnet-config: [op-node-op-reth, kona-node-op-geth, kona-node-op-reth]
        include:
          - devnet-config: op-node-op-reth
            client: op-node
            engine: op-reth
          - devnet-config: kona-node-op-geth
            client: kona
            engine: op-geth
          - devnet-config: kona-node-op-reth
            client: kona
            engine: op-reth
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          submodules: true

      - uses: ./.github/actions/setup
        with:
          channel: stable
          components: llvm-tools-preview

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false

      - uses: taiki-e/install-action@just

      - uses: taiki-e/install-action@cargo-llvm-cov

      - uses: jdx/mise-action@v3       # installs Mise + runs `mise install`

      - name: Setup Go 1.23.8
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.23.8'
          cache-dependency-path: "**/go.sum"

      - name: acceptance tests for ${{ matrix.devnet-config }}
        run: |
          if [ "${{ matrix.client }}" = "kona" ]; then
            source <(cargo llvm-cov show-env --export-prefix)
          fi
          just acceptance-tests "${{ matrix.client }}" "${{ matrix.engine }}" 
          if [ "${{ matrix.client }}" = "kona" ]; then
            cargo llvm-cov report --lcov --output-path "acceptance_tests_${{ matrix.devnet-config }}.lcov"
          fi
      
      - name: Upload coverage to codecov.io
        if: ${{ matrix.client == 'kona' }}
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: acceptance_tests_${{ matrix.devnet-config }}.lcov
          flags: e2e
          env_vars: OS,RUST
          name: node-sysgo-tests-common
          verbose: true



